services:
#    billandgo.example:
#        class: BillAndGoBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    limitation:
        class: BillAndGoBundle\Controller\DefaultController
        arguments: ["@service_container"]
